# Configuration
language: objective-c
osx_image: xcode10.2
xcode_sdk: iphonesimulator12.1
podfile: ios/Podfile

# Continuous Integration Script
#   fastlane scan - runs the application tests
# script:
# - fastlane scan