# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.73.0"

default_platform :ios

platform :ios do

    desc "Create an .xcarchive"
    lane :archive_for_client do |options|

        bundle_id = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
        team_id = ENV['team_id']
        scheme = ENV['scheme']
        configuration = ENV['configuration']
        project_path = ENV['project_path']
        workspace_path = ENV['workspace_path']
        target_name = ENV['target_name']

        disable_automatic_code_signing(
            path: project_path,
            team_id: team_id,
            use_automatic_signing: false,
        )

        xcarchive(
            archive_path: "build/#{target_name}.xcarchive",
            workspace: workspace_path,
            scheme: scheme,
            xcargs: "CODE_SIGN_IDENTITY= CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO",
        )

    end

    desc "Build for Testflight"
    lane :build_for_testflight do |options|

        setup_travis

        bundle_id = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
        team_id = ENV['team_id']
        scheme = ENV['scheme']
        configuration = ENV['configuration']
        project_path = ENV['project_path']
        workspace_path = ENV['workspace_path']
        target_name = ENV['target_name']

        disable_automatic_code_signing(
            path: project_path,
            team_id: team_id,
            use_automatic_signing: false,
            code_sign_identity: "iPhone Developer"
        )

        match(
            readonly: true
        )
        
        gym(
            scheme: scheme,
            configuration: configuration,
            workspace: workspace_path,
            clean: true,
            include_bitcode: false,
            include_symbols: true,
            export_method: "development",
            export_team_id: team_id,
            output_directory: "build"
        )

    end

end

# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
